# Generated by Django 5.2.16 on 2026-09-11 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0181_item_provider_episode_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="order_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="order_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalseason",
            name="order_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="provider_episode_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="season",
            name="order_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EpisodeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("series_id", models.CharField(max_length=500)),
                ("key", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("catalogue", models.JSONField(default=dict)),
                ("revision", models.CharField(max_length=64)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="episode_orders",
                        to="app.item",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historicaltv",
            name="active_episode_order",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="app.episodeorder",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="episode_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="app.episodeorder",
            ),
        ),
        migrations.AddField(
            model_name="tv",
            name="active_episode_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trackers",
                to="app.episodeorder",
            ),
        ),
        migrations.CreateModel(
            name="EpisodeOrderChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("mappings", models.JSONField(default=list)),
                ("before_state", models.JSONField(default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.episodeorder",
                    ),
                ),
                (
                    "tv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.tv"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="episodeorder",
            constraint=models.UniqueConstraint(
                fields=("show", "provider", "series_id", "key", "revision"),
                name="app_episode_order_revision_unique",
            ),
        ),
    ]
