# Generated by Django 5.2.16 on 2026-09-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0184_alter_metadatabackfillstate_field"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="podcastepisode",
            index=models.Index(fields=["episode_uuid"], name="podcast_ep_uuid_idx"),
        ),
    ]
