# Generated by Django 5.2.16 on 2026-09-23 22:59

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def backfill_status(apps, schema_editor):
    """Give existing episode history records the status they were saved with.

    Records predating status tracking default to Completed. A dropped play is
    recoverable from its tracked `dropped` flag. An open play that has not
    finished yet takes its current status on the records without an end date.
    A play that was open and has since finished keeps Completed throughout;
    its earlier status was never recorded.
    """
    Episode = apps.get_model("app", "Episode")
    HistoricalEpisode = apps.get_model("app", "HistoricalEpisode")

    HistoricalEpisode.objects.filter(dropped=True).update(status="Dropped")

    open_plays = Episode.objects.exclude(status__in=["Completed", "Dropped"])
    HistoricalEpisode.objects.filter(
        id__in=open_plays.values("id"),
        end_date__isnull=True,
        dropped=False,
    ).update(
        status=Subquery(
            open_plays.filter(id=OuterRef("id")).values("status")[:1],
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0187_anime_entry_source_basicmedia_entry_source_and_more"),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name="historicalepisode",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
