# Generated by Django 5.2.16 on 2026-09-23 23:25

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0188_historicalepisode_status"),
        ("users", "0135_merge_20260918_0021"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticsSyncState",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("generation", models.BigIntegerField(default=1)),
                ("hot_synced_generation", models.BigIntegerField(default=0)),
                ("heavy_synced_generation", models.BigIntegerField(default=0)),
                ("heavy_synced_at", models.DateTimeField(blank=True, null=True)),
                ("synced_day", models.DateField(blank=True, null=True)),
                ("last_marked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "full_sweep_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="StatisticsDirtyDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("token", models.UUIDField(default=uuid.uuid4)),
                ("marked_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "day"),
                        name="statistics_dirty_day_unique_user_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StatisticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_name", models.CharField(max_length=32)),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("generation", models.BigIntegerField(default=0)),
                ("built_day", models.DateField()),
                ("built_at", models.DateTimeField()),
                ("schema_version", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "range_name"),
                        name="statistics_snapshot_unique_user_range",
                    )
                ],
            },
        ),
    ]
