# Generated by Django 5.2.16 on 2026-09-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0189_statistics_sync_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="opencritic_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When OpenCritic was last asked about this game",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="opencritic_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="Matched OpenCritic game ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="opencritic_percent_recommended",
            field=models.FloatField(
                blank=True,
                help_text="Share of OpenCritic critics who recommend the game",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="opencritic_review_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of top critic reviews on OpenCritic",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="opencritic_score",
            field=models.FloatField(
                blank=True, help_text="OpenCritic top critic average (0-100)", null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="opencritic_tier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="OpenCritic tier: Mighty, Strong, Fair or Weak",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="opencritic_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="OpenCritic page for the matched game",
                max_length=500,
            ),
        ),
    ]
