# Generated by Django 5.2.16 on 2026-09-25 13:40

import app.models.media
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0190_item_opencritic_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="basicmedia",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="boardgame",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="comic",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="comicissue",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="manga",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="music",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
        migrations.AddField(
            model_name="tv",
            name="scored_at",
            field=app.models.media.ScoreMonitorField(
                blank=True, default=None, monitor="score", null=True
            ),
        ),
    ]
